### ISSUE TITLE
Suggestions on the Monix chapter

### ISSUE THREAD

**Issue by alexandru** [denisftw/advanced-scala-code#1]
Hi Denis, 

First of all I must say that the chapter and the given samples are engaging, thanks for including this in your book.

Couldn't find your email, so I might as well post some review notes here.

> Unlike Futures that need an ExecutionContext for most of their operations, Monix Tasks only require it for actual execution.

This isn't accurate. `Future` also needs the `ExecutionContext` for actual execution, the difference between them is that with `Future` any transformation that happens (e.g. `map`, `flatMap`) happens immediately when the call happens, with the `Future` implementation triggering a `Runnable` in the given `ExecutionContext`, which is why the `ExecutionContext` is required on each method call.

So the actual difference is that `Task` has lazy behavior. With it you can specify any transformation you want without it triggering an evaluation yet, with the actual evaluation happening only when `runAsync` gets called.

> javaFuture.cancel(true)

That boolean parameter is called `mayInterruptIfRunning`, it specifies that if the thread has started executing the logic it can be interrupted, in general it has no effect if `true` being sort of legacy and even if the underlying implementation allows interrupting the thread, I think it's a bad idea. I find it healthier to just let it be, once it started, because the JVM has no way to safely stop a thread once it started. This is just a note - I'm not even sure if you should change that to `false`. 

> Alternatively, you can move the following two lines inside the Task.create method:

Referring to `asyncHttpClient.prepareGet`, this should actually be the recommended practice, because `Task` has lazy behavior and this is cool because it allows the client to restart the task in case of error, something that `Future` cannot do. `Task` and functions that return `Task` should trigger side-effects only after `runAsync`. You can leave it outside for sure, but you only need to do that if you need to share this request  with something else and I don't see the need for that.

Another reason to place everything in `Task.create` is that, when you make the request, you can probably get Java exceptions. You know how Java libs tend to be designed. You'd expect that callback to give you an error _only through_ the callback mechanism, but in my experience that doesn't happen with a majority of Java libraries. Which is why I would place that logic in `Task.create` and surround that `try/catch`, reporting the error by means of `cb.onError(ex)`. 

This is because for functions that return `Task` or `Future`, people expect error reporting and handling to happen only by means of `Task` or `Future`. And as an implementation detail `Task.create` will catch errors for you but it can only log them (by means of `scheduler.reportError`) but it cannot complete the `Task` for you, so `try/catch` of unorthodox Java stuff is recommended ;-)

``` scala
def using[A, C <: { def close() }](closeable: C)(block: => A): A = ???

using(br) {
  import monix.reactive.Observable
  val linesO = Observable.fromLinesReader(br)
}
```

I understand what you're trying to do here, however this will not work, because `using` has synchronous behavior, whereas `Observable` has asynchronous behavior. The only way to make this piece of code work is to do an `Await.result` somewhere, which I'm personally against doing. Basically when you go async, everything has to be async, including resource handling.

However, you don't even need to do a `using` here, because `Observable.fromLinesReader` will already trigger that `close()` for you, both [in normal conditions](https://github.com/monixio/monix/blob/v2.0.1/monix-reactive/shared/src/main/scala/monix/reactive/internal/builders/LinesReaderObservable.scala#L114) or when [a cancel happens](https://github.com/monixio/monix/blob/v2.0.1/monix-reactive/shared/src/main/scala/monix/reactive/internal/builders/LinesReaderObservable.scala#L154).

And you know what it would be cool for you to do? To use `Observable.defer` here as well and open that reader on each `subscribe`, because `Observable` is very much alike `Task` and the same arguments hold: you want the ability to restart that `Observable`.

This suggestion is optional, but I think the `using` stuff is a bug and should be fixed.

Cheers,

**Comment by denisftw** [comment]
Hi Alexandru!

Thanks a lot for this amazingly detailed post. My email was in the farewell-chapter, but I think GitHub is even better, because of code highlighting :)

I will definitely fix all these problems, but just to clarify your first point: `Future` needs an `ExecutionContext` for both operations _and execution_, while Monix `Task` needs it only for execution, right? Or, in other words, what I missed was the execution part of `Future`? 

Or, what you suggest is to shift the explanation to discussing different design choices?

**Comment by alexandru** [comment]
If by operations you mean `map` and `flatMap`, in the context of `Future` that's also execution, due to its design. Say we have a `val source2 = source.map(_ + 1)`. This creates another `Future` reference, that registers a callback that will fire (on another logical thread) as soon as the `source` is complete. Say we do another `val source3 = source2.map(_ + 2)`, which will also register a callback that will fire (on another logical thread) when `source2` is complete.

My favorite way of explaining this difference is to say that `Future` is strict, whereas `Task` is lazy. When you get a `Future` reference, whatever process that's meant to complete it has most likely already started.

**Comment by denisftw** [comment]
Got it!

I've just fixed the most significant issues (`Future`/`Task` differences, the `using` stuff and `prepareGet`) and republished the book. And I'll also apply other suggestions in a couple of days. 

Thanks again! :)

**Comment by denisftw** [comment]
/cc @alexandru 

I applied other suggestions including using `Observable.defer` (also added some info about `defer` in the text) and updated the subproject to Monix 2.0.2. Should be good now :)

I think it makes sense to close this issue, but feel free to re-open it if you have other concerns.

**Comment by alexandru** [comment]
Sure, let's close it.
